name: Run unit tests

on: [push, pull_request]

jobs:

  test:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: BDSA2020.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0


    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
